alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: '<SENDER_EMAIL>'  
      smtp_auth_username: '<SENDER_EMAIL>'     
      smtp_auth_password: '<GMAIL_APP_PASSWORD>'
      smtp_require_tls: true                
    route:
      receiver: 'email'                       # Default receiver for alerts
      group_by: ['alertname', 'job']          # Group alerts by these labels
      group_wait: 5s                         # Wait before sending grouped alerts
      group_interval: 1m                      # Interval between grouped alerts
      repeat_interval: 4h                     # Interval before re-sending unresolved alerts
      routes:
      - match:
          alertname: Watchdog                 # Route Watchdog alerts to null receiver
        receiver: 'null'
    receivers:
    - name: 'email'
      email_configs:
      - to: '<RECEIVER_EMAIL>'             # Recipient email address
        send_resolved: true                 # Send notifications when alerts resolve
    - name: 'null'                          # Null receiver for ignored alerts